version: '3.8' 

services: 
  # postgres:
  #   image: postgres:latest
  #   container_name: ad1ee_cungus_db
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #   ports:
  #     - "5440:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  ad1eecungusservice: 
    container_name: ad1ee_cungus_service
    # depends_on:
    #   - postgres
    image: ad1eedotnet/cungus:nossl
    build: 
      context: .
    ports: 
      - "8080:5000" 
      # - "8081:5001"
    environment: 
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_Kestrel_Certificates_Default_Password}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${ASPNETCORE_Kestrel_Certificates_Default_Path}
      - SECRET=${SEKRITDOKUMINTS}
    volumes:  
      - ${USERPROFILE}/.aspnet/https:/https/  

  ad1eecunguswebserver:
    container_name: ad1ee_cungus_frontend
    build:
      context: ./frontend
    ports:
      - "3030:3030"
    environment:
      - NODE_ENV=production
volumes:
  postgres_data: